### ISSUE TITLE
Why? What?

### ISSUE THREAD

**Issue by iteles** [dwyl/dwylbot#1]
https://github.com/dwyl/contributing/issues/68#issuecomment-275401984

https://github.com/dwyl/contributing/issues/70

https://github.com/dwyl/contributing/issues/78#issue-204253967

**Comment by ghost** [comment]
@iteles should these be added to the Why and What sections of the readme?

**Comment by ghost** [comment]
Closing in favour of https://github.com/dwyl/dwylbot/issues/89
