### ISSUE TITLE
only add merge conflict label on the specific PR

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#102]
If a PR has a merge conflict then dwylbot add a message error on this PR but also propagate the error to the other open PRs. We need to be sure that the PR are properly checked before adding the message error. Bug found on LDMW

Possible source of the issue: 
the ```mergeable``` property of the PR is ```null``` instead of ```true``` or ```false```. We might need to add more waiting time to let github update the status. Otherwise maybe the property is not always updated so it might stay to a ```null``` value. In this case we dwylbot can't decide if the PR has some merge conflicts so it shouldn't report the error in this case

**Comment by ghost** [comment]
Linked to https://github.com/dwyl/dwylbot/issues/162

**Comment by ghost** [comment]
👍
