### ISSUE TITLE
Travis error with empty migrations folder

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#11]
Tavis is failing tests when a Phoenix project doesn't have any migrations. The folder /priv/repos/migrations is empty and is not pushed to Github so travis can't see it and returns this eror:
```
** (Mix) Could not find migrations directory "priv/repo/migrations"
```

One solution is to add the migrations folder to the .gitkeep file. Otherwise I just created an empty migration with just ```mix ecto.gen.migration start```. I think I will use this migration later on.

I'm not sure about adding .gitkeep file in a project just to please Travis. Do people use .gitkeep?

**Comment by iteles** [comment]
Good question to add to the learn-phoenix repo too to contain the knowledge and people are watching that one :+1:

**Comment by ghost** [comment]
@SimonLab shall we move this to 'learn-phoenix' and close this issue?

**Comment by nelsonic** [comment]
Fixed. 👍
