### ISSUE TITLE
When to add reviewers to a PR?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#116]
linked to #62 (assign user to the PR based on the reviewers and add the "awaiting-review" label)

I think reviewers should only be added when the PR is ready to be reviewed, does this sound right?

In case if a reviewer is added before the PR is ready maybe we should check if the "in-progress" label is on the PR before adding the "awaintin-review" label. However not a lot of people add the "in-progress" label at the moment.
Any thought on this?

**Comment by Cleop** [comment]
Personally I only add a reviewer when a PR is ready to be reviewed unless... I'm dealing with a comment on the PR if I've had a review that's rejected it, in which case I would put the `in-progress` label on, leave the reviewers as they were (but unassign them and assign myself) and remove the `awaiting-review` until I'm done. Then I'd remove the `in-progress` and myself as an assignee and pop the `awaiting-review` back on and reassign it to them.

**Comment by ghost** [comment]
Agreed that reviewers should only be added when a pr is ready for review - the inprogress label should always be on when something is being worked on and should be removed when sending for review

**Comment by samhstn** [comment]
I personally like knowing what I'm going to review as soon as possible even if it isn't ready (I can be added as a reviewer, but the pr can be in progress and not yet assigned to me)

But it seems like I'm alone with this

I'm fine to not have this configured and can see reasons to not have this set up, but just adding my opinion as [I originally thought this was a bug](https://github.com/dwyl/dwylbot/issues/122)

**Comment by ghost** [comment]
Closing as this question was answered
