### ISSUE TITLE
Deploy Phoenix server on Heroku

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#12]
- [x] Create Heroku account
- [x] Add a postgress database
- [x] Push application to Heroku from Github
 
Do we need to specify some settings to run a Phoenix app on Heroku?

**Comment by jruts** [comment]
@SimonLab https://github.com/dwyl/learn-phoenix-framework/blob/master/heroku-deployment.md

**Comment by jruts** [comment]
Main thing is adding the 2 build packs (one for elixir and one for phoenix). And of course your environment variables.

**Comment by SimonLab** [comment]
@jruts Thanks for the link, I'll try this and we should be able to have a first (and very basic) online version

**Comment by jruts** [comment]
@SimonLab let me know how it went. I think you are the first one who is going to try setting it up based on this documentation. If you think it can be improved, just shoot!

**Comment by SimonLab** [comment]
It's alive, https://dwylbot.herokuapp.com/webhooks
Thanks @jruts I just have one comment concerning the secret_key_base see https://github.com/dwyl/learn-phoenix-framework/issues/56

Otherwise the guide looks good :+1: . I didn't see a link to it from the readme of https://github.com/dwyl/learn-phoenix-framework it might be worth to add one!

@iteles @markwilliamfirth you can now try to access the app on heroku see the link at the top

**Comment by iteles** [comment]
@SimonLab You added the please-test label but kept adding commits - should @markwilliamfirth be closing this issue once confirmed or not really?

**Comment by SimonLab** [comment]
Yes, this issue can be close I think as #13 has been merged, I won't have any more commits to add linked to this issue now. Thanks @itelesbot for the reminder :+1:

**Comment by ghost** [comment]
lol @itelesbot
