### ISSUE TITLE
time with in-progress label?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#120]
Should we calculate the total amount of time the "in-label" label has been applied to an issue. When close dwylbot could maybe post a comment with the time spent on the issue based on this calculation.
It might take a bit of time to impelment as it requires to get all the status and and data possible of the issue.
Is this a good idea or should we leave it for now?

**Comment by ghost** [comment]
This is a good idea and should be done - it also relates to functionality in the time app, but I think we should get all the assignee / label features working first (as we already have the majority of the logic for these and therefore these are quick wins) and then begin working on time tracking following that

**Comment by SimonLab** [comment]
Maybe this feature should be delegated to Time. Like in the issue #20 (Trigger Time when "in-review" label is applied) we could trigger Time with the label "in-progress"

**Comment by ghost** [comment]
Closing as this will be part of Time's remit
