### ISSUE TITLE
Adding reviewers, dwylbot automatically assigns assignees

### ISSUE THREAD

**Issue by samhstn** [dwyl/dwylbot#123]
I would like dwylbot to add these automatically (which it does 👍), but I would also like it to not notify me that I didn't assign them, it seems to be doing that, see [here](https://github.com/LDMW/app/pull/405#issuecomment-310129582).

@SimonLab is this a bug?

**Comment by SimonLab** [comment]
I wasn't sure to add a comment on this case but I think I will add one now and see the feedback :+1:

**Comment by ghost** [comment]
@SimonLab in this case how does dwylbot decide who to assign?

**Comment by samhstn** [comment]
@markwilliamfirth Dwylbot should assign as a reviewer whoever has been assigned to the pr when the pr is in the awaiting-review state.

**Comment by ghost** [comment]
👍
