### ISSUE TITLE
Unable to add access to dwyl/time-apple-watch-app repo

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/dwylbot#131]
I tried to follow the installation instructions and failed at the first hurdle. 😢 

**tried to click dwyl organisation so that I could select time-apple-watch-repo**
<img width="836" alt="screen shot 2017-06-22 at 18 19 09" src="https://user-images.githubusercontent.com/2305591/27447064-834cabc2-5777-11e7-8f79-613228959f0a.png">
**get this error message when clicking through**
<img width="1236" alt="screen shot 2017-06-22 at 18 19 15" src="https://user-images.githubusercontent.com/2305591/27447085-a241cb52-5777-11e7-8e0a-476135e4f393.png">

I'll just assign the `bug` label here, but I feel this is a **P1** issue as I am unable to add dwybot to a repo.

**Comment by iteles** [comment]
Aaaaaaaah, this might be a permissions issue 🙄 

Try again now @sohilpandya

**Comment by sohilpandya** [comment]
@iteles still getting the same issue. 😟

**Comment by SimonLab** [comment]
Yes it's a permission issue. I think you have to be an admin of dwyl to install DwylBot in this case.

**Comment by iteles** [comment]
@SimonLab An admin of the org, not just and admin of the repo?

**Comment by SimonLab** [comment]
Yes I think you need to b an admin of the org. I've try to install the dwylbot on dwylbot and had the same error. A Github App is linked to an organisation and from there during the installation process you can choose to install the application on all the repositories of the organisation or just selecting one repository.
It's true it's a bit strange that when you try to install an application without the right permission Github doesn't show a nice error message, but I guess Github App is still quiet new still.

**Comment by iteles** [comment]
In that case, we need instructions for how org admins provide access for dwylbot to new repos. I'm happy to do this.

I'd also like to test what happens if I give dwylbot access to _all_ the repos, does dwylbot magically start commenting?

**Comment by ghost** [comment]
>I'd also like to test what happens if I give dwylbot access to all the repos, does dwylbot magically start commenting?

I think so - as far as I understand only one admin needs to install it one time and then it works for everyone

**Comment by SimonLab** [comment]
To add dwylbot on new repo, the user will just need to get back to the Github configuration page of the application and find the repo on the list (ie just need to repeat the installation steps described on the Readme: https://github.com/dwyl/dwylbot#install). We can precise this on the Readme :+1: 

If you decide to install dwylbot on all the repositories of the organisation, then it will be active on all of them. However dwylbot will only check for new errors, it won't be able to scan the repos for existing errors

**Comment by ghost** [comment]
I will add these instructions to the readme:

dwylbot.herokuapp.com
Manage dwylbot installations
Configure
**Pick Organisation**
Repository access
Only select repositories
**Select a repository**
Save

**Comment by ghost** [comment]
Looks like this (https://github.com/dwyl/dwylbot/issues/131#issuecomment-321338154) has already been done 

https://github.com/dwyl/dwylbot/#install
