### ISSUE TITLE
Duplicate identical messages in Pull Request?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwylbot#136]
It _appears_ that @dwylbot is posting duplicate comments, e.g: https://github.com/LDMW/cms/pull/49
![image](https://user-images.githubusercontent.com/194400/27796537-4224a5e4-6002-11e7-9777-ef4cef7bad94.png)

@SimonLab you're _probably_ aware of this ... but I could not find an issue for it. 🤔

**Comment by SimonLab** [comment]
Yes this is linked to the following issue: #129 
I think this one start to be annoying and I'll try to fix it as soon as possible. I need first to finish the PR #134 which will create the structure to tackle this issue, thanks for the reminder :+1:
