### ISSUE TITLE
Doing things I've already done / Dwylbot Repeating itself

### ISSUE THREAD

**Issue by harrygfox** [dwyl/dwylbot#142]
I think the screenshot below is fairly self-explanatory:
I added reviewers, assignees and a label, only for dwylbot to tell me to do that and then do it twice itself. 

![screencapture-github-oxfordabstracts-application-pull-3752-1502280506423](https://user-images.githubusercontent.com/7805691/29120869-1fb45440-7d04-11e7-95b0-a2aef9439e67.png)

**Comment by sohilpandya** [comment]
Yep @harrygfox, I think it's logged here https://github.com/dwyl/dwylbot/issues/129

**Comment by ghost** [comment]
Closing in favour of #129
