### ISSUE TITLE
UX - Message Wording

### ISSUE THREAD

**Issue by harrygfox** [dwyl/dwylbot#143]
![image](https://user-images.githubusercontent.com/7805691/29120964-76c04320-7d04-11e7-9d4d-f2a63ca13077.png)

Whenever I see this message I always expect to see a *"but.. you did something wrong"* or I see the *"no something"* and it makes me think "I've done something wrong.... what have I done wrong".

Actually that's not what dwylbot is saying. Maybe it's just me, but I'd prefer the **first words** to be something like: "Good news!". I don't want to feel like dwylbot is scolding me for my poor github things. I want it to encourage me to do better.

**Comment by ghost** [comment]
Linked to https://github.com/dwyl/dwylbot/issues/105#issuecomment-310026449

**Comment by ghost** [comment]
Closing in favour of #84
