### ISSUE TITLE
Parsing json payload of a webhook

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#15]
The server is now able to catch the payload sent by Github:
```
{
  "action": "created",
  "issue": {
    "url": "https://api.github.com/repos/dwyl/dwylbot/issues/9",
    "repository_url": "https://api.github.com/repos/dwyl/dwylbot",
    "labels_url": "https://api.github.com/repos/dwyl/dwylbot/issues/9/labels{/name}",
    "comments_url": "https://api.github.com/repos/dwyl/dwylbot/issues/9/comments",
    "events_url": "https://api.github.com/repos/dwyl/dwylbot/issues/9/events",
    "html_url": "https://github.com/dwyl/dwylbot/pull/9",
...
```

and my controller has the following create action:

```
  def create(conn, %{"payload" => payload}) do
    IO.puts "Post request to /webhooks received!"

    IO.puts payload.action
    conn
    |> put_status(201)
    |> json(%{ok: true})

  end
```

I manage to print the payload but I fail to extract the "action" property with payload.action:

```
Request: POST /webhooks/create
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.apply("{\"action\":\"labeled\",\"issue\":{\"url\"
```

I've also try to use a pattern match on the action with
```
  def create(conn, %{"payload" => %{"action" => action}}) do
    IO.puts "Post request to /webhooks received!"
    IO.puts action
    conn
    |> put_status(201)
    |> json(%{ok: true})

  end
```

but get also an error

```
(Phoenix.ActionClauseError) bad request to Dwylbot.WebhooksController.create, no matching action clause to process request
```

@shouston3 @jackcarlisle do you have any suggestions on how to access the values of a json payload?

**Comment by jruts** [comment]
@SimonLab , can you try Map.get(payload, "action") ?
Or can you print out how the actual payload looks like? `IO.puts "${inspect payload}"` or `IO.inspect payload`

**Comment by SimonLab** [comment]
```
(BadMapError) expected a map, got: "{\"action\":\"created\",\"issue\":{\"url\":\"https://api.github.com/repos/dwyl/dwylbot/issues/9\",...
```
It looks the the payload still contains a string, is this right? I thought Phoenix could automatically parse a  stringify json with Poison

**Comment by jruts** [comment]
Don't you need to explicitly decode it with Poison? `Poison.decode! payload`

**Comment by SimonLab** [comment]
@jruts Thanks a lot it worked! I try to see how I can add the decode function into the api pipeline to parse automatically the payload on each requests:

```
  pipeline :api do
    plug :accepts, ["json"]
   # plug :parsepayload or something similar
  end
```

**Comment by jruts** [comment]
@SimonLab you will indeed need a plug parser for that.
https://hexdocs.pm/plug/Plug.Parsers.html

more specifically: https://hexdocs.pm/plug/Plug.Parsers.JSON.html#content

**Comment by jruts** [comment]
@SimonLab a more detailed example: http://absinthe-graphql.org/guides/plug-phoenix/

Scroll over to the Phoenix section (ignore the absynthe bit)

**Comment by jruts** [comment]
Or even this one: https://elixir-examples.github.io/examples/phoenix-framework-from-http-request-to-response

**Comment by jruts** [comment]
Sorry for the ramble, I am pretty sure you can figure it out pretty easily by yourself! Good stuff :)

**Comment by SimonLab** [comment]
Thanks for all the links :+1: I'll read through the doc and try to understand the details of the parsers

**Comment by jruts** [comment]
@SimonLab a last tip: https://engineering.appcues.com/2016/02/02/too-many-dicts.html

Read 2 and 5 carefully. You will want to use a struct, not just decode the json string into a map.

Have fun :)

**Comment by SimonLab** [comment]
At the moment I parse the stringify payload with ```Poison.decode!(payload)``` in my create action. I'm still looking for another way to parse the json maybe by creating a Plug. Also the endpoint.ex file already parse the body of the requests see [this line](https://github.com/dwyl/dwylbot/blob/f786d4243a83b0c8d6685bbc9fc12c6653b9bc68/lib/dwylbot/endpoint.ex#L25) but the payload is still stringify so I'm still missing something and don't quiet yet understand how the payload is created from the post request.
Some more research to be done on this but at this stage it's not a blocker anymore

**Comment by jruts** [comment]
@SimonLab here is an example of a similar plug: https://dockyard.com/blog/2015/08/05/building-json-api-endpoints-with-phoenix

**Comment by iteles** [comment]
@jruts Thanks for all the input! 😍 
You're a peach 🍑

**Comment by SimonLab** [comment]
Thanks for all the links!! My main issue when parsing the payload was in fact a mistake from my part when I created the webhooks on Githbub, see #19 . Phoenix **automatically** parse the json payload to a map :tada:
