### ISSUE TITLE
Create dwylbot Github user

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#16]
An easy solution to allow the dwylbot to create comment is to use a Github Oauth token for a user account (It doesn't seem possible for an organisation to create a comment)

@iteles do you have a preference for the name of the new user Github account (dwylbot?) and for the email address linked to it?

see https://chatbotslife.com/create-your-own-bot-for-github-part-2-bc8b5267a280#.wdhkqhkqo which are the main steps for a Github bot

**Comment by ghost** [comment]
@SimonLab I think it might already exist! https://github.com/dwylbot

**Comment by nelsonic** [comment]
@SimonLab password for @dwylbot user sent to you privately. 👍

**Comment by SimonLab** [comment]
Thanks @nelsonic I didn't manage to connect with the password you give, has it change or maybe I'm doing something wrong? I'm using my account for now to test

**Comment by SimonLab** [comment]
it's alive thanks :+1:

**Comment by nelsonic** [comment]
@SimonLab thanks for confirming. 👍
