### ISSUE TITLE
Remove oauth

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#172]
The application contains some endpoints linked to some oauth authentication feature. This authentication was used at the beginning of this project when Github apps wasn't yet implemented.
dwylbot doesn't use any authentication so we can remove all this unnecessary code

**Comment by nelsonic** [comment]
@SimonLab what _access_ can the GitHub application have?
e.g: 
+ create/update labels?
+ create columns in GitHub Project?

**Comment by SimonLab** [comment]
- create/update labels -> I don't think and I'm not sure if Github apps have access to this permission
- create columns in Github Project, same I don't think dwylbot can do this at the moment.

I will check if the "repository administration" permission can allow dwylbot to access this updates

At the moment dwylbot has the following permissions:
![image](https://user-images.githubusercontent.com/6057298/36117040-355f2530-1030-11e8-9d75-ef884d880b8b.png)

The two only write access are on the issues and pull requests. I'll create an issue to review the permissions list and see if all of them are necessary. We could always update the permissions depending on the new rules implemented.

Otherwise dwylbot is listening to the follwing events, again it's something that we can review and update
![image](https://user-images.githubusercontent.com/6057298/36117216-b5ebe7b0-1030-11e8-8756-bbbd99e8b270.png)

**Comment by nelsonic** [comment]
thanks @SimonLab 😉
