### ISSUE TITLE
spike 2, notification on invalid issues/PRs

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#21]
Based on our rules (see #5) an issue can be valid or invalid. One way of improving #7 is to let @dwylbot posting a comment only after a certain period of time to let the user the time to add more modifications to an issue/PR to make it valid. So we need a notification system where @dwylbot will be told to comment after a certain time on a specific issue if this one is invalid.
One possilbe implementation:
- save all the issues/PRs in Postgres
- for each Github weebhook events, save the event in Postgres; run a [rule engine](https://en.wikipedia.org/wiki/Business_rules_engine) to determine if the issue/PR linked to the event is valid or not and; update the status of the issue/PR; save the time when @dwylbot is supposed to comment for invalid issue/PR
- For each invalid issue where the delay time is passed trigger @dwylbot which will comment with a description of all the rules that need to be fixed

I think there are two main spike on this process:
- how to build a rule engine
- how to notify @dwylbot that it needs to comment on a specific issue

The first point can be relatively implemented by hardcoding the rules like in #7 (we might want to find a more abstract way to define rules later on)
The second point might need a bit more thought. At the moment I have two ideas on how to implement this:
- create a "setInterval" function in Elixir that will check for invalid issue in Postgress with the time notification expired
- Read and see if we can use the [notify](https://www.postgresql.org/docs/9.0/static/sql-notify.html) function from Postgres. I think I will prefer to try to implement this solution has it looks a bit nicer. see also https://blog.garage-coding.com/2016/05/25/redesigning-notification.html

Is this process clear? Any other thoughts or recommendations welcome!

**Comment by SimonLab** [comment]
- http://stackoverflow.com/questions/32085258/how-to-run-some-code-every-few-hours-in-phoenix-framework

**Comment by nelsonic** [comment]
@SimonLab nice one. 😉

**Comment by SimonLab** [comment]
After a bit more research I don't think Postgres notify feature is the right way to go as it seems to trigger event when a modification is applied to some tables but I don't think there is a way to trigger an event with notify based on timestamp store in a table. 
Moreover for the purpose of learning Elixir/Phoenix I think using a similar solution based on the stackoverflow question above is better choice. This will require a bit more time to learn and undesrtand some concepts based on processes, OTP and GenServer but I think it is worth it.

**Comment by ghost** [comment]
@SimonLab can this be closed?

**Comment by SimonLab** [comment]
This spike let me discover Github App. We are currently deploying the app on the [Github marketplace](https://github.com/apps/dwylbot)
