### ISSUE TITLE
Use model on Github payload

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#22]
We can use a model which takes the responsibility to parse the payload send by the Githbub webhooks see [this lines](https://github.com/dwyl/dwylbot/blob/d28c1790f820c48b62360a450c3c2d953aa71cc5/web/controllers/webhooks_controller.ex#L10-L16)

A changeset function will allow us to cast and validate the fields received in the payload

**Comment by ghost** [comment]
@SimonLab what's the next steps for this issue?

**Comment by SimonLab** [comment]
Creating a model is a bit an overkill at the moment. We are using Poinson.parse to get the json payload to a map and select the few properties that we need.
