### ISSUE TITLE
Module for our rules?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#23]
[This line](https://github.com/dwyl/dwylbot/blob/d28c1790f820c48b62360a450c3c2d953aa71cc5/web/controllers/webhooks_controller.ex#L18) define the rule for the "in-progress label without assignee". At the moment all the logic is implemented in the controller but as we will add more rules it might be worth to create a separate module which can contains our set of rules.

**Comment by nelsonic** [comment]
It would be _amazing_ to be able to declare the rules in a text file. but for now a "pipeline" is fine. 👍

**Comment by ghost** [comment]
@SimonLab are you doing this using cases at the moment? https://github.com/dwyl/dwylbot/pull/80#discussion_r122250250

Is all logic still in the controller? Can we time-estimate how long it would take to
1. Create a module for rules
2. Declare rules in a text file

**Comment by SimonLab** [comment]
Each rules have now their own modules, see [issues rules folder](https://github.com/dwyl/dwylbot/tree/master/web/controllers/rules/issue) and [PR rules folder](https://github.com/dwyl/dwylbot/tree/master/web/controllers/rules/pr)

Concerning describing the rules in a text file, this might be a bit more tricky. The idea behind doing this is I think to be able to let user create their own rules. This will require some spike and research, and I don't think I will be able to give an estimate before this. I think it worth to create an issue for this: "create custome rules for users"?

**Comment by ghost** [comment]
>Each rules have now their own modules, see issues rules folder and PR rules folder

Amazing!

> I think it worth to create an issue for this: "create custome rules for users"?

Great idea 👍  https://github.com/dwyl/dwylbot/issues/96
