### ISSUE TITLE
Save events, issues and PRs in Postgres

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#24]
To keep track of which issues are valid or invalid we can store the state of the issues and PRs in Postgres. The webhooks event swill modify the states of the issues and PRs. Then @dwylbot will be able to add comments on Github on the right issues/PRs just by querying for invalid elements in Postgres.

So we need to define a schema to represent issues/PRs and webhooks events in Postgres

**Comment by nelsonic** [comment]
@SimonLab what are your thoughts on using ElasticSearch to store the Webhook request payload(s) ? relates to: https://github.com/dwyl/learn-phoenix-framework/issues/64

**Comment by SimonLab** [comment]
I'm still not sure and need more thinking about the type and amount of data we need to store in a database to allow dwylbot to work properly. However Elasitcsearch is great for logging events so it might be a good choice to investigate

**Comment by ghost** [comment]
@simonlab can this be closed?

**Comment by SimonLab** [comment]
I don't user Postgres at the moment as dwylbot check directly the payload from a webhook and reply directly on Github if there is an error.
However we might need to user a database for more complicated rules later on. Closing for now, I will reopoen when necessary
