### ISSUE TITLE
Replace Tentacat by HTTPoison

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#25]
[Tentacat](https://github.com/edgurgel/tentacat) is a nice Github wrapper, however it doesn't yet provide all the features provided by the Github API (especially removing labels, see also [this comment](https://github.com/dwyl/dwylbot/issues/7#issuecomment-285386964)).

@dwylbot won't have a lot of API called to Github to execute, mostly adding a comment on issues and PRs and removing/adding labels so we can
- [ ] use HTTPoison to send http request to the API
- [x] Create a PR on Tentacat to add the feature we would like to have

**Comment by nelsonic** [comment]
@SimonLab good plan. Tentacat is using https://github.com/edgurgel/httpoison under the hood, so we might as well use it for our _specific_ requests. but ... but it might be an idea to send a PR to tentacat for the _specific_ methods we need... 🤔

**Comment by SimonLab** [comment]
I've created a PR to add the remove label method into Tentacat. A new version of Tentacat will be realese soon so we might just be able to continue to use it instead of creating or own github api wrapper with HTTTPoison.

**Comment by ghost** [comment]
@SimonLab does https://github.com/edgurgel/tentacat/pull/114 mean this is now solved? What do you mean by released?

**Comment by SimonLab** [comment]
Yes now we can use Tentacat now :+1:

**Comment by ghost** [comment]
Awesome! Does that mean we can close this one? Or do we still need to do http requests with HTTPoison?

**Comment by SimonLab** [comment]
yes closing for now. I will continue to use Tentacat at the moment and if other method need to implemented we can reopen it.
