### ISSUE TITLE
Feature Spike: Delay dwylbot posting

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#26]
the stackoverfow answer (http://stackoverflow.com/questions/32085258/how-to-run-some-code-every-few-hours-in-phoenix-framework) define a way to trigger some work at a specific time interval. However to understand the details and logic of the code I need a to do a bit more research on concurrent programming (see part 2 of "Programming Elixir 1.3" book):

- [x] processes
- [ ] node
- [ ] OTP Severs
- [ ] OTP Supervisors
- [ ] OTP Application
- [ ] Task and Agent

I should then be able to understand this:

```
defmodule MyApp.Periodically do
  use GenServer

  def start_link do
    GenServer.start_link(__MODULE__, %{})
  end

  def init(state) do
    schedule_work() # Schedule work to be performed at some point
    {:ok, state}
  end

  def handle_info(:work, state) do
    # Do the work you desire here
    schedule_work() # Reschedule once more
    {:noreply, state}
  end

  defp schedule_work() do
    Process.send_after(self(), :work, 2 * 60 * 60 * 1000) # In 2 hours
  end
end
```

This spike wil take some time but once this will allow us to crate a strong architecture for @dwylbot

**Comment by ghost** [comment]
@SimonLab I understand this now works - ok to close?

**Comment by SimonLab** [comment]
The logic linked to #58 is a bit different. Instead of using processes described on this issue (otp, task, agent...) I'm just using ```Process.sleep``` which just block the program.
I still need to learn more about the processes and especially how to use them concurrently. I think we will need to use them for more complicated rules, for example getting all the inactive issues of all the repositories, Github doesn't give any event for this kind of functionality so dwylbot will need to get the information itself and that's where processes will be useful I think

**Comment by SimonLab** [comment]
closing for now as we don't need to use more complex OTP feature at the moment. Will reopen when we need them
