### ISSUE TITLE
dwylbot Heroku App Access (please/thanks!)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwylbot#28]
@SimonLab please add me to the `dwylbot.herokuapp.com` so that I can read the logs. thanks! 👍

**Comment by iteles** [comment]
@nelsonic Added you as a collaborator (I think your gmail had been added previously)

**Comment by iteles** [comment]
@nelsonic Added you as a collaborator

**Comment by nelsonic** [comment]
Sweet. Thanks! ❤️
