### ISSUE TITLE
review Github OAuth flow

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#31]
- [x] The [request action](https://github.com/dwyl/dwylbot/blob/84ec7fef1a5075664730d21a6fcee3eb25d97b09/web/router.ex#L34) action is not defined in the AuthController, do we need it?

- [x] The [Ueberauth.Strategy.Helpers alias](https://github.com/dwyl/dwylbot/blob/84ec7fef1a5075664730d21a6fcee3eb25d97b09/web/controllers/auth_controller.ex#L5) is defined but not used in AuthController

- [x] Review the needed scope needed for dwylbot, the default scope are ```["public_repo", "user"]``` see https://developer.github.com/v3/oauth/#scopes

- [x] Review the callback action where a ["Successfully authenticated" message](https://github.com/dwyl/dwylbot/blob/84ec7fef1a5075664730d21a6fcee3eb25d97b09/web/controllers/auth_controller.ex#L17) is displayed when the callback catch a [failure](https://github.com/dwyl/dwylbot/blob/84ec7fef1a5075664730d21a6fcee3eb25d97b09/web/controllers/auth_controller.ex#L14)

- [x] The Github token seems to be saved directly in the user cookie. I think the cookie/session is [encrypted](http://www.phoenixframework.org/docs/sessions#section-cookies) by Phoenix I'm wondering if adding the token directly to the session is the right way to do it? How to use the token in other endpoints?More research/learning to do on this step

- [x] Add OAuth Github diagram and explanation to the readme, I spend each time more than an 1h to remember all the details of the OAuth flow and I'm always afraid to miss an important step

**Comment by nelsonic** [comment]
@SimonLab I'm investigating Auth today. look forward to seeing your notes. 😉

**Comment by ghost** [comment]
@SimonLab I tested the authentication and it works 👍
