### ISSUE TITLE
Who wants to review the PRs(Elixir/Phoenix)?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#33]
I will start to create some new PRs soon on this project. I know some people are already busy with other projects but it would be good to have someone review my PR.
@eliascodes @shouston3 @Danwhy @nelsonic let me know if you have time and if you are happy to have a look at the code and to be assigned.

**Comment by shouston3** [comment]
I don't mind reviewing

**Comment by nelsonic** [comment]
@SimonLab I'd _love_ to read your code (_and leave reviews on your PRs!_)
I can only do so in the evenings ...

**Comment by eliasmalik** [comment]
@SimonLab I still haven't started learning Elixir yet, so pass 😆

**Comment by SimonLab** [comment]
@eliascodes it might be a good way to start learning it :wink:  the project is not too complicated at this stage

**Comment by ghost** [comment]
Closing as Sam and Dan have been reviewing 👍 

@eliascodes let us know if you change your mind about learning some Elixir!
