### ISSUE TITLE
Add credo and deploy

### ISSUE THREAD

**Issue by ghost** [dwyl/dwylbot#34]
Add credo and deploy

**Comment by SimonLab** [comment]
Adding [credo](https://github.com/rrrene/credo) will report some errors on the project. I will need some time to go over them so I've added a 2h estimation

**Comment by SimonLab** [comment]
Just had a look at the documentation of credo: http://credo-ci.org and install the package in mix.exs then running credo ```mix credo --strict``` gave me:
![screenshot from 2017-05-10 13-30-11](https://cloud.githubusercontent.com/assets/6057298/25898678/0d920436-3585-11e7-9ed6-b7a81838cdf7.png)
![screenshot from 2017-05-10 13-30-26](https://cloud.githubusercontent.com/assets/6057298/25898679/0d92be76-3585-11e7-8284-d74c8f0c9d39.png)

note: Unfortunately there the info notice about my version of Elixir can't be resolve easily on Fedora. The latest package at the moment is 1.3 for Elixir. I might be able to compile Elixir 1.4 but it might take a while to do it on my machine

**Comment by ghost** [comment]
Uh oh ... @SimonLab [seems like](http://forums.fedoraforum.org/showthread.php?t=314091) fedora might not be ideal for elixir? Ubuntu might be a solution?

**Comment by SimonLab** [comment]
I prefer to keep fedora at the moment as I just installed it on my new thinpad x230 :tada: I will use the configuration file for the buildpadk on heroku to select the Elixir version 1.3 and I'm sure 1.4 will be available soon on fedora, see also #45

**Comment by SimonLab** [comment]
This is now resolved with #44
