### ISSUE TITLE
Describe the main technical steps of dwylbot

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#36]
As a developer I want to have the main steps and main features I need to implement for dwylbot described in a technical documentation (or issues) so that I can have a general idea of the project and have a clear idea of what needs to be researched and implemented.

At the moment I can think about the main steps of the dwylbot flow:

- Authorise the user with GitHub login #30 #31
- Request list of the user's public repositories and apply dwybot status on each repository (active/inactive) #38 
- Request list of the organisation's repositories where the user is an administrator of the organisation and apply dwylbot status on each repository #37 
- Save user and list of repositories in Postgres #38 #41
- Activate/deactive dwylbot on a repository (create/delete webhook on GitHub repo) #38 
- How should dwylbot react to a GitHub webhook notification? This step requires more thought on how to implement it whilst still being able to scale the application #39

**Comment by SimonLab** [comment]
@markwilliamfirth if you could review these steps and let me know if they are clear enough or if you see any other steps that I missed :+1:

**Comment by ghost** [comment]
@SimonLab looks great!

**Comment by SimonLab** [comment]
all the main steps are now implemented directly by using dwylbot as a Github App
