### ISSUE TITLE
Review: Mention Bot

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/dwylbot#4]
Facebook seem to have a bot on GH to help the workflow. One of them is the [mention bot](https://github.com/facebook/mention-bot)

Has anyone had a chance to use it? Wanted to ask if this was worth reviewing at all?

**Comment by SimonLab** [comment]
linked to #35 (competitive analysis) 
From the description: "Automatically mention potential reviewers on pull requests.
" It's a nice to have but I think we want dwylbot to check for a set of rules described in a contributing file not just assigning people on PR

**Comment by nelsonic** [comment]
@sohilpandya _lots_ of companies have _some_ kind of GH <> Chat integration.
But 99.9% of teams don't have a _well-defined_ GH "Workflow".
Facebook's "bot" _barely_ scratches the _surface_ of what we're going to do. 😉 
@dwylbot is going to be a "Workflow Simplifier" and "Coach"; it will both _apply_ labels to issues/PRs, automatically reject/re-assign them if there are `merge-conflicts`, CI issues or lack of description in descriptions. 
I haven't found a _similar_ project on GH. But would _love_ it if someone can link to one! 👍

**Comment by ghost** [comment]
Closing as has been looked into and other projects issue here https://github.com/dwyl/dwylbot/issues/35
