### ISSUE TITLE
database postgres initial structure

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#41]
To be able to complete #38 (display the dwylbot status, acitve/inactive for the public repositories) we need first to create the structure of the database with migration in phoenix. we will need:
- [ ] A User table with the main information updated each time a user loggin: the info will come from Github so if the user update her Github account we need to update the information on our database also. The user Github token use for sending API request will only be store in encrypted session on the browser so we don't collect all tokens in our database which limit the risk if our database is compromised.
- [ ] A  Repositories table which store the main information about the repos. We need to decide what relation type the repositories table has with the user table, many-to-many or unique link. For organisation mutiple users can be admin of a repos and a multiple repos can be linked to one user so I think many-to-many should be the structure we would use

Once the tables have been created we can start parsing the response from the Github API and inserting the values into the tables

**Comment by SimonLab** [comment]
We only want to insert a new user in the database. For that we can add a constraint on the changeset which checks that the Github username inserted in Postgres is unique by using ```|> unique_constraint(:username)```. However it is not possible to use changeset.valid?() function to check the uniqueness constraint, we need to attempt to insert the new changeset then ```Repo.insert``` will return the error. 

From the Ecto starting guide(https://hexdocs.pm/ecto/getting-started.html#content):

"changeset.valid? will not check constraints (such as uniqueness_constraint). For that, you will need to attempt to do an insert and check for errors from the database. It’s for this reason it’s best practice to try inserting data and validate the returned tuple from Friends.Repo.insert to get the correct errors, as prior to insert the changeset will only contain validation errors from the application itself."

**Comment by SimonLab** [comment]
Read https://hexdocs.pm/ecto/Ecto.Schema.html#many_to_many/3 to create a many_to_many relation between users and repositories

**Comment by nelsonic** [comment]
@SimonLab do you have a Schema Diagram for the DB? if not, do you have time to make one? 🤔

**Comment by ghost** [comment]
@simonlab what's the update on this one?

**Comment by SimonLab** [comment]
dwylbot is not using any database at the moment. The installation process is handle by [dwylbot Github app](https://github.com/apps/dwylbot)
