### ISSUE TITLE
Automatic deploy on Heroku

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#45]
It would be great to enable the automatic deploy on Heroku when a PR is merged. At the moment Heroku return an error:

```
All dependencies up to date
-----> Copying hex from /app/.mix/archives/hex-0.16.0
-----> Compiling
** (Mix) You're trying to run :dwylbot on Elixir v1.4.2 but it has declared in its mix.exs file it supports only Elixir ~> 1.3.1
 !     Push rejected, failed to compile Elixir app.
 !     Push failed
```

**Comment by SimonLab** [comment]
I can create a configuration file on the root of the project which tell Heroku to select a specific Elixir version
see https://github.com/HashNuke/heroku-buildpack-elixir#configuration

**Comment by ghost** [comment]
@SimonLab will test this to see if it works after the PR is made

**Comment by SimonLab** [comment]
Elixir is now up to date on my machine so we should be able to use the last version on heroku and on localhost

**Comment by SimonLab** [comment]
done with #46
