### ISSUE TITLE
Use docker (compose) as a development/test stack

### ISSUE THREAD

**Issue by JoseCage** [dwyl/dwylbot#50]
Hello developers/nerds/geeks/friends. I hope I have not breached any rules regarding [contribution](https://github.com/dwyl/contributing) to dwyl projects.

![bitmoji](https://render.bitstrips.com/v2/cpanel/10212995-227153730_1-s4-v1.png?transparent=1&palette=1&width=246)

I've been looking through existing projects, and particularly in "**[Learn Elixir](https://github.com/dwyl/learn-elixir)**" and "**[Learn PhoenixFramework](https://github.com/dwyl/learn-phoenix-framework)**" since I'm focused on learning both. And before this I had a doubt of which I have a suggestion.

**_Question _**:
* Have you ever used docker or another stack in development? Or you install the dependencies/packages on the machine (host)?

In case you do not use any stack, my suggestion, in particular for this repository ([dwylbot](https://github.com/dwyl/dwylbot)) is to give the option of using docker as well. Since in addition to avoiding "installing a lot of software on the host", there are guarantees that all project developers are using the same system configuration, which can reduce errors and incompatibility ..

-------------------------------
In case the suggestion is valid, I have created a docker image (I think if it is approved I will name it dwyl/elixir) which is based on the official elixir image. I already have installed in the image: **Node** _v6.10.3_ (npm and yarn), **Elixir** _v1.4.2_ (hex, rebar, phoenix).

------
Sorry if there is any spelling/grammar error in my text .. I am still learning English, so any criticism/correction is welcome.

*Thank you all**.

**Comment by ghost** [comment]
@josecage probably best to post this question in here: https://github.com/dwyl/technology-stack 👍

**Comment by SimonLab** [comment]
@JoseCage sorry for the late reply. I'm not using at the moment Docker. From the littler reading I've done about it, to make it work on a project just a config file needs to be created, is this right? 
The code on this repo is still changing a lot but i you think adding Docker won't have any side effect on the project, I'm happy for you to create a PR :+1:

**Comment by JoseCage** [comment]
Thanks for your answer @markwilliamfirth @SimonLab ..

> From the littler reading I've done about it, to make it work on a project just a config file needs to be created, is this right?

Yes. We just need a config file (for docker) that we will use to serve/run the **dwylbot**..

I will create a PR as soon as i can and you can see/test..
