### ISSUE TITLE
Should we create a Github App?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#51]
Github has created a [marketplace](https://github.com/marketplace) where people can search and install application that extend the Github functionalities. I think the main goal for Github is to get some revenue from the pay versions of these apps: "Note: As part of the Marketplace Developer agreement, GitHub receives a 25% revenue share from GitHub Marketplace listings." see https://developer.github.com/apps/adding-integrations/listing-apps-on-github-marketplace/about-github-marketplace/.
To make it easy for developers to create and offer applications on the marketplace, Github has create "Github App". The main way for an App to access the Github API is now to use jwt and a private key to authenticate. However the OAuth are also wrapped in Github App and can be used to authenticate a specific user. I'm still looking at the Github App documentation and I'm creating a dummy simple app to tests the new functionalities.
**From this I'd like to create a "learn-github-app" repo which can help us to decide if we want to create dwylbot as an app and if we want to list it on the Github marketplace.**

My first thought about apps, is that it is easier to install as Github take care of it, however if we create a paid version of dwylbot we will have to give 25% to Github. I also need to find out more about the small prints when an app is on the marketplace (rights, permissions, licences?)

Any ideas, feedback, comments or suggestions on why we should use the Github marketplace or why we should avoid it?

linked to #47 
see also https://developer.github.com/apps/

**Comment by ghost** [comment]
Sounds like a good idea to investigate further - since the app store is relatively new this could be a great opportunity for us to get something out there and generate publicity

**Comment by SimonLab** [comment]
From a spike yesterday I manage to
- create a Github App
- Install the Github App on repositories using the Github UI interface
- Execute API requests authenticated as a Github App using a private key
- Execute API requests authenticated as an Github App installation using token see https://github.com/SimonLab/github_app/issues/1#issuecomment-305554654

All the process to add/remove dwylbot on repositories decribed on the issue https://github.com/dwyl/dwylbot/issues/30 can now be done directly with the Github Interface. However it would be nice to show on a dwylbot page which repositories have dwylbot installed and which one can get the application. Unfortunately at the moment I don't think the API let you install an Github app on your profile or organisations see the [Github API doc](https://developer.github.com/v3/apps/installations/):
- List repositories
- List repositories accessible to the user for an installation
- Add repository to installation
- Remove repository from installation
This means that a user need first to install the app via Github then active/inactive the application (via github or with the api)

**Comment by SimonLab** [comment]
yes let's use Github App, a new shiny thing to play with :tada:
