### ISSUE TITLE
Use new api based on OAuth of Github Apps credentials

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#52]
When moving dwylbot to a Github App (see #51), Github provides new credentials for OAuth. This new credentials don't allow us to access as much api endpoints as before:
![image](https://cloud.githubusercontent.com/assets/6057298/26790275/09d9609c-4a0b-11e7-879b-e8732f945140.png)
Here we can't get the list of the public repos of the logged in user anymore.  Instead of getting the list of public repos I suggest to follow the userflow described [here](https://github.com/dwyl/dwylbot/issues/30#issuecomment-305769407).
So the first step after login is to display the list of all installations of dwylbot available to the user by using the following endpoint: https://developer.github.com/v3/apps/#list-installations-for-user.

- [x] Create a simple http client for Github app that allow us to send api request to this new endpoint (Tentacat doesn't implement at this stage the api for Github Apps, linked to #25 )
- [x] Could we use a dumb Github App to run our tests or should we create a mock?
- [x] Display the json response on the website

**Comment by ghost** [comment]
This works
