### ISSUE TITLE
Spike implementation of dwylbot

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#6]
- [x] How to capture events from Github: new PR, new issues, changes label, change assignees...?
- [x] How to listen to these event with Elixir/Phoenix?
- [x]  Do we need an authentication process to capture Githbub events?

Implement a prototype of the dwylbot to get a better idea of the technical challenges
Create implementation doc for creating the first dwylbot version

**Comment by SimonLab** [comment]
some links to read:
-  [Github webhook](https://developer.github.com/v3/repos/hooks/) API doc
- [Github webhook](https://developer.github.com/webhooks/) Guide
- Elixir wrapper for Github API, [Tentacat](https://github.com/edgurgel/tentacat)
- Elixir package to manage webhooks, [Grapple](https://github.com/camirmas/grapple)
- [Elm process-bot] (https://github.com/process-bot/contribution-checklist)
- [PubSubHubbub](https://github.com/pubsubhubbub/PubSubHubbub)
- Phoenix & webhooks [discussion](https://elixirforum.com/t/phoenix-and-webhooks/721/3)
- [Simpler alternative to phoenix for web-hooks endpoint?](https://elixirforum.com/t/simpler-alternative-to-phoenix-for-web-hooks-endpoint/3806)

**Comment by SimonLab** [comment]
So:
- 1) Create manually the webhooks (go to settings then webhooks) on the repository (or organisation). We can later on do this step automatically with the Github API but for a first version the UI provided by Github to add webhooks is good
- 2) Create a server with at least a post route (ex: /webhooks) which will get the payloads send by the webhooks. I've manage to get this quickly done with [SimpleServer]. (https://github.com/SimonLab/simpleServer) and [ngrok](https://ngrok.com/) (to expose my localhost server to the Github webhook instead of using Heroku)
![webhook](https://cloud.githubusercontent.com/assets/6057298/23658847/ed874c62-033b-11e7-9d75-076c23a9f941.png)

- 3) create the logic of the server. This is the main work to be done. The logic of the rules from #5 needs to be implemented and triggered depending of the action type received on the payload of the post request.

- 4) Use Github API to post comment, change assignee, change label... to indicate how to follow the [contributing guide](https://github.com/dwyl/contributing) 

So Phoenix Server + Heroku + Github webhooks for the first version. 

Once the main parts of the application are done (server, tests, doc, heroku app), the idea is to have a process or architecture that allow us to create new rules quickly and easily. I will focus on this once I finish #3 as it will give me a better idea on how to abstract rules.

@iteles @nelsonic @markwilliamfirth any comments or more details you would like to see (I will add more issue when I start on #3 that will explain the implementation)?

**Comment by nelsonic** [comment]
@SimonLab this is an _excellent_ start! (_well done for spiking the web hook so quickly!_) 🐎 
Keep going! it sounds like you should have something useful soon! 👍 
I will _suggest_ that you start _storing_ some of the GitHub web hook request payloads somewhere (_your choice. e.g: `.json` on your computer or in a DB if you can_) so that you can re-play them as "mock" data for tests. 😉 
Thanks for doing this! You're a `hero`!  ❤️  ✅  🚀

**Comment by iteles** [comment]
@SimonLab I'd love to have an issue in learn-phoenix about using APIs and the need for tentacat ❤️

**Comment by nelsonic** [comment]
@SimonLab do we have a JSON file with a sample GitHub Webhook request payload?

**Comment by SimonLab** [comment]
I've create a few [json files](https://github.com/dwyl/dwylbot/tree/master/github_webhooks) in the project using the [issue test](https://github.com/dwyl/dwylbot/issues/14)

**Comment by nelsonic** [comment]
@SimonLab yeah, sorry I saw the https://github.com/dwyl/dwylbot/tree/master/github_webhooks folder shortly after asking the question and _forgot_ to update this issue to inform you that I knew.
Thanks for your great work on this! ❤️  ✅

**Comment by ghost** [comment]
@SimonLab what's the next steps with this issue? The implementation documentation?

**Comment by ghost** [comment]
@simonlab can this be closed?

**Comment by SimonLab** [comment]
We are now using Github App which give us webhooks and a way to install dwylbot via the Github [marketplace](https://github.com/apps/dwylbot)
