### ISSUE TITLE
Feature: reminder to assign reviewing if PR has awaiting review label

### ISSUE THREAD

**Issue by ghost** [dwyl/dwylbot#63]
When a PR has "awaiting-review" label and the PR's author belongs to the team of the project then add a comment to the PR with "Please assign someone to review your PR, thanks"

**Comment by SimonLab** [comment]
The difficulty here is to know if the author of the PR has the right to assign someone. I'm not sure that Github provide enough information to determine this, need to investigate

**Comment by ghost** [comment]
@simonlab have opened another issue for that here: https://github.com/dwyl/dwylbot/issues/95 👍

**Comment by SimonLab** [comment]
If the label "awaitin-review" has been added to the PR, this means that the user who added the label has also the right to add an assignee. So I don't think #95 (permission of user on PR) is directly linked to this issue at the end.

**Comment by ghost** [comment]
@SimonLab this doesn't appear to work

https://github.com/dwyl/dwylbot/pull/118

**Comment by SimonLab** [comment]
@markwilliamfirth dwylbot as added a comment to ask the user to assign someone on the PR:
https://github.com/dwyl/dwylbot/pull/118#issuecomment-310093078

I think it's fine or do I miss something?

**Comment by ghost** [comment]
Sorry I got this one mixed up with #64 (that one doesn't post a comment)

This one works 👍
