### ISSUE TITLE
Feature: automatic assignment of updating-tests label

### ISSUE THREAD

**Issue by ghost** [dwyl/dwylbot#65]
When a PR has "awaiting-review" label and the tests are failing then add the label "updating-tests" and assign the author of the PR

**Comment by SimonLab** [comment]
We need to know how to get the event of a failing tests. This might also depend of the CI used on the project. We can start with Travis as it is the most CI tool used on our project. If when manage to catch the event then the functionality is the same as in #58

**Comment by SimonLab** [comment]
At the moment:
- we can get an event when Travis as some failing tests, https://developer.github.com/v3/activity/events/types/#statusevent
- The first branch name on the property branches of the event should be the branch of the PR
- we need to get the list of all the open PR to select the correct one, we will be then able to get the id of the issue linked to the PR to then be able to change the labels, assignee...

**Comment by ghost** [comment]
@SimonLab I removed and readded the awaiting-review label here https://github.com/dwyl/dwylbot/pull/118 but it didn't trigger the updating tests label

**Comment by SimonLab** [comment]
the rule is trigger when the tests have finish to run and return an error (also on the pr #118 it's the coverage failing not the test) not when the awaiting label is added, we can create an issue for this new trigger

**Comment by ghost** [comment]
The first step for this works: https://github.com/dwyl/dwylbot/pull/118#issuecomment-321292657

Although it does not add an "updating-tests" label

**Comment by iteles** [comment]
The need for an `updating-tests` label should really be discussed in https://github.com/dwyl/labels first. We're trying hard to keep our labelling system to only those that really add value to the process which is why we discuss each label before adding it there.

**Comment by ghost** [comment]
To be honest I'm not sure if we even need the updating tests label as this isn't currently part of our process and dwylbot by definition should reflect the dwyl process - happy for this to be marked as complete
