### ISSUE TITLE
define waiting time per rule

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#74]
At the moment if some errors are find we are waiting 30s before checking again if an issue has still the errors before commenting and notify the user the errors.
Some errors might have different time notification, we should define this duration per rule instead of having a global one.

**Comment by ghost** [comment]
Agreed this should be customisable per rule! For now let's test 30s as the default when making rules

**Comment by ghost** [comment]
Can't test individual waiting time per rule as it is technical, but waiting time does work 👍
