### ISSUE TITLE
New issue must have a description

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#76]
Ensuring issues have descriptions, dwylbot should explain good practices for issues when this happens

**Comment by SimonLab** [comment]
:stop_sign: @#{login}, the issue has no **description!**
Please add more details to help us understand the context of the issue.
Please read our [Contribution guide](https://github.com/dwyl/contributing#part-1-describe-your-question-the-idea-or-user-story-in-an-issue) on how to create issue
Thanks! :heart:


other suggestion for the error message?

**Comment by ghost** [comment]
⚠️ @#{login}, this issue has no description. Please add a description to help others understand the context of this issue.

--

You can read more about how to create an issue in a dwyl repository [here](https://github.com/dwyl/contributing#part-1-describe-your-question-the-idea-or-user-story-in-an-issue).
Full guidelines for contributing to a dwyl repository can be found [here](https://github.com/dwyl/contributing/blob/master/README.md).

**Comment by ghost** [comment]
<img width="353" alt="screen shot 2017-06-21 at 15 12 20" src="https://user-images.githubusercontent.com/5732209/27388674-16cddad6-5694-11e7-8fa2-3920448d9c0c.png">

@SimonLab this works, but notice your own app is running here too

https://github.com/dwyl/dwylbot/issues/117
