### ISSUE TITLE
List or organisation and repositories needed?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#78]
After a few tests with some dwyler, it seems that the oauth authentication and displaying the list of organisation and repositories where dwylbot is active is confusing and doesn't give much information of what dwylbot is doing and how to use it:
![image](https://user-images.githubusercontent.com/6057298/27177176-55a822ce-51bd-11e7-8ed7-3be94bfdfb95.png)

I think I would prefer to just have one nice looking html page which describe what is dwylbot and how to install it directly with Github marketplace. We should also add a link to dwyl.com, if dwylbot become popular this would improve our SEO.
If we need more feature directly linked to oauth we could add back the authentication but at the moment I don't think it necessary.

maybe the following structure for the page:
- Title
- what is dwylbot
- why dwylbot
- how to install dwylbot (ie small tutorial on how to use github market place)
- how to use it (sync your labels with the label app, then just continue using github normally, dwylbot will guide you and help you to enhance your workflow)
- created by dwyl.com
- footer with links to github, twitter,...?

Would you agree @markwilliamfirth @nelsonic @iteles @shouston3?
If this proposal is agreed @markwilliamfirth do you have time to create some of the content?

**Comment by ghost** [comment]
Yep - this is something we should definitely do (and I can create some content), but for the moment we should focus on building in features that help our workflow. Optimising the installation process, oauth authentication and org/repo lists should definitely be revisited after we've built in the required features.

**Comment by SimonLab** [comment]
Ok, I think the dwylbot first version will be ready to test soon as we have now a few rules implemented.
Instead of rewriting the the existing page I will update the Readme of the repo with information on how to install and use dwylbot, does this sound good @markwilliamfirth?

**Comment by ghost** [comment]
@simonlab sounds great 👍

**Comment by ghost** [comment]
lol - classic dwylbot

<img width="546" alt="screen shot 2017-06-19 at 17 16 55" src="https://user-images.githubusercontent.com/5732209/27294935-1cdf0576-5513-11e7-8b3d-8dbd2797a544.png">

**Comment by SimonLab** [comment]
images installation step on github:
![image](https://user-images.githubusercontent.com/6057298/27295764-fadffbb2-5515-11e7-85fb-dc267e462c15.png)

![image](https://user-images.githubusercontent.com/6057298/27295790-0e296884-5516-11e7-9840-6e41c153e67c.png)

![image](https://user-images.githubusercontent.com/6057298/27295823-2971c898-5516-11e7-88e0-6e37e7acd5ba.png)

**Comment by SimonLab** [comment]
resolved with #100
