### ISSUE TITLE
create phoenix server

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#8]
Create a Phoenix server with one endpoint: POST /webhooks that log the payload received. The payloads will be sent by Github webhooks each time an event is trigger.

**Comment by SimonLab** [comment]
Some first comment on creating a Phoenix API:
- Do not use the browser pipeline for the api, otherwise the protect_from_forgery plug will block your request
- Do not use ```resource "/webhooks", only: [:create]``` . This will create a route for a PUT request. Github webhooks send a POST request
- I test my post endpoit with curl: ```curl --data '{"id": 43}' localhost:4000/webhooks/create -H "Content-Type: application/json"``` Do not forget to add the Header with the right content-type, the api piple use the accepts plug with json: 
```
  pipeline :api do
    plug :accepts, ["json"]
  end
```
- your data ( '{"id": 43}') should also be a valid json otherwise Poison will send a malformed error

My next step is to add some tests for Travis and try to deploy the application on Heroku

**Comment by nelsonic** [comment]
@SimonLab looking good so far. 👍 
I will look at this with the PR. 😉

**Comment by SimonLab** [comment]
resolved with #10
