### ISSUE TITLE
open PR without a descripton

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#81]
Add a comment which warns the user to add a description on a PR
see https://github.com/dwyl/dwylbot/pull/79#pullrequestreview-44316470

**Comment by SimonLab** [comment]
We need first to know the type of the event, issue or pull request, to be able to apply the right set of rules.
We can get this information from the ```x-github-event``` header of the request, with phoenix: ```Plug.Conn.get_req_header conn, "x-github-event")```

Here is the list of all the possible type of events: https://developer.github.com/webhooks/#events

**Comment by ghost** [comment]
https://github.com/dwyl/dwylbot/pull/90
dwylbot doesn't comment when there is a description 👍 

https://github.com/dwyl/dwylbot/pull/91
dwylbot does comment when there is no description 👍
