### ISSUE TITLE
Goal/objective for dwylbot

### ISSUE THREAD

**Issue by iteles** [dwyl/dwylbot#89]
As a person working on the dwylbot project, I would like to have a clearer understanding of what the purpose of dwylbot is so that I can factor that into decisions on prioritisation and how much effort to allocate to a specific task.

---

I didn't realise this was unclear from the outset, my apologies!

**Comment by nelsonic** [comment]
@iteles the purpose of dwylbot is to automate dwyl's workflow so more people can contribute to our project(s) without humans having to "_reprimand_" them for not applying labels or including a description in their issue etc. 
The _real_ benefit will come when we begin to _automate_ "coaching" on how to _communicate_ better with fellow contributors. e.g: https://github.com/dwyl/dwylbot/issues/98

**Comment by iteles** [comment]
The main questions here are:
+ _Enforce_ process vs _suggest_ process
+ dwyl-only vs 'anyone can use it'

**Comment by SimonLab** [comment]
My view with dwylbot is in the first step the same as @nelsonic , we want a tool that improve our workflow and how we contribute/work on project. Then the next step is to make dwylbot generic enough to let other company create their own rules and have their own version of the bot.

At this stage I think dwylbot should _suggest_ a process to follow. If we need to _enforce_ a rule it might have more effect when it's explain by a real person. I'm also worry is if a tool try too much to enforce a tool then users won't use it anymore. We need to find the right balance with user testing.

**Comment by ghost** [comment]
Agreed that the MVP is suggest and dwyl-only
