### ISSUE TITLE
How to collect feedback?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#94]
dwylbot is deployed on a few repositories already and will start to post a few warning/error messages on issues and PRs.
Should we add a line at the end of each warning/error message to explain how user can give feedback, something like:

"If you have any question, suggestion, complain or contribution linked to dwylbot, please let us know by opening an issue on the [dwylbot repository](https://github.com/dwyl/dwylbot/issues)"

does this sound good?

**Comment by ghost** [comment]
@simonlab Yes! Great idea! Please do this 👍

**Comment by SimonLab** [comment]
Is this text better?

  Any questions, complaints, feedback, contributions?
        [![Discuss](https://img.shields.io/badge/discuss-with%20us-brightgreen.svg?style=flat)](https://github.com/dwyl/dwylbot/issues "Discuss your ideas/suggestions with us!")

**Comment by iteles** [comment]
We can also use https://dwyl-feedback.herokuapp.com/feedback/new for anonymous feedback 😊

**Comment by SimonLab** [comment]
@iteles where do you receive the private feedback, on a dwyl email address?

**Comment by ghost** [comment]
@SimonLab it goes to my email 👍

**Comment by ghost** [comment]
This works 👍
